### ISSUE TITLE
i686 build failure

### ISSUE THREAD

**Issue by antonio-rojas** [ximion/appstream-generator#19]
0.5.0 doesn't build on 32 bits with gdc:

appstream-generator ~master: building configuration "application"...
```
source/utils.d:373:13: error: function std.net.curl.HTTP.Protocol!().onReceive (uint delegate(ubyte[]) callback) is not callable using argument types (void)
             downloader.onReceive = (data) => onReceiveCb (dest, data);
             ^
source/utils.d:379:13: error: function std.net.curl.FTP.Protocol!().onReceive (uint delegate(ubyte[]) callback) is not callable using argument types (void)
             downloader.onReceive = (data) => onReceiveCb (dest, data);
             ^
gdc failed with exit code 1.
make: *** [Makefile:3: all] Error 2
```

**Comment by ximion** [comment]
Yes, I see this on Debian too and even with https://github.com/ximion/appstream-generator/commit/3c0bdb9557df0695d2e2d01fc769c0974a5f36fb applied the last few issues don't get fixed.

They are also complete nonsense in my opinion, and I wonder whether this is actually a compiler bug.
Can you try building with LDC and see if that exhibits the same behavior?

**Comment by antonio-rojas** [comment]
Same error with gdc, dmd and ldc.

**Comment by ximion** [comment]
Okay, then it's likely real - question is why does it works on amd64, and what does this error message want to tell us?
`onReceive` is called using a delegate, not `void`, so this should be fine. I'll check this out when I arrived in Berlin, probably need to ping the D community about this, because I am rather clueless here (or simply not seeing the obvious bug).
