### ISSUE TITLE
media is always put in `media` directory

### ISSUE THREAD

**Issue by iainlane** [ximion/appstream-generator#32]
I want to override the `MediaBaseUrl` to something else so that I can have `appstream-dep11`'s media under `/media`. The problem is that asgen always puts the media in a `media` directory on the filesystem, so you can't just expose the export directory, you need to transform it to match the `MediaBaseUrl` by renaming.

Maybe a `MediaDirectory` configuration option that is used for the output directory and also appended to the `MediaBaseUrl` in the output, if it is present or something?

I think in reality I'll just keep using `media` because `ImmutableSuites` means there's not a conflict between `media/main` (as-dep11) and `media/suite/main` (asgen), so this isn't that urgent for me.

**Comment by ximion** [comment]
I always wanted to make this a bit more configurable, but when going all the way we would have
`HtmlBaseDir`, `MediaBaseDir`, `HintsBaseDir`, and `ExportDir` or `CacheDir` to put temporary files under... So so far when this came up I told people to symlink things, but maybe we should resolve this in a more configurable way at some point.

Reusing media for both generators is fine, there should be no conflicts (and maybe we can update the Xenial data even, I had a few ideas based on your suggestion, but couldn't develop anything further because of -ENOTIME)

**Comment by iainlane** [comment]
Yeah, it's lucky that there are no conflicts - it makes the filesystem layout kind of ugly but I don't think I care. :-)

**Comment by ximion** [comment]
You care, you filed a bug ^^ - but you probably don't care enough to invest a lot of time into it.

Why I want this to be solved at some point maybe, is to make asgen easier to embed in other tools, so you e.g. can pass the JSON dynamic parameter to the tool instead of creating lots of static workspaces for each repo.
