### ISSUE TITLE
Fonts don't appear in the appstream db

### ISSUE THREAD

**Issue by aleixpol** [ximion/appstream-generator#7]
From https://github.com/ximion/appstream/issues/38

**Comment by ximion** [comment]
asgen would need proper support for building icons and "screenshots" for fonts. Also, the fonts in distribution packages will need to ship metainfo files (which is something we have little influence on).

**Comment by ximion** [comment]
I just checked, in Debian there are *zero* fonts shipping a metainfo file... Fedora is patching all packages to supply one.
This is really an issue.

**Comment by ximion** [comment]
This is resolved in master now, some minor issues still need to be clarified though.
And most importantly, distributions or font upstreams need to ship AppStream metainfo files.

**Comment by ximion** [comment]
Fonts support is now enabled by default, refer to https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Fonts.html on how to write the necessary metainfo files to make fonts appear in the collection metadata.
Unfortunately we require metainfo files for fonts, since we can't reliably auto-detect the right values via heuristics, and some required data simply doesn't exist.
