### ISSUE TITLE
Formatting the code with dfmt

### ISSUE THREAD

**Issue by Cogitri** [ximion/appstream-generator#76]
It'd be nice if appstream-generator was formatted with dfmt to allow for a consistent style across all files.

**Comment by ximion** [comment]
I'll just say no to that for now, at least unless Dfmt can be tweaked to follow the coding style of asgen at the moment, which is basically AppStream's coding style (space before brackets, brackets in-line with condition statements, ...) but with 4-spaces instead of tabs for indentation. And I really don't want to change that, the churn would be massive and also pretty pointless (and make future bisecting hard).
If Dfmt grew flags to configure it to replicate the current style as much as possible, I would be very open to having it though.

**Comment by Cogitri** [comment]
dfmt does have some flags, I'll see if I can get it to look like the current source of a-g.
