### ISSUE TITLE
Please help understanding what's wrong with this log

### ISSUE THREAD

**Issue by basilgello** [ximion/appstream-generator#98]
We have added metainfo file to Kodi: https://github.com/xbmc/xbmc/pull/20142 but appstream-generator still complaints `no-metainfo`: https://appstream.debian.org/sid/main/issues/kodi.html Also, I don't see what causes `ancient-metadata` warning.

The prebuilt Kodi package is here: https://packages.debian.org/sid/amd64/kodi/download

And big thanks from Kodi team in advance! :)

**Comment by ximion** [comment]
The `ancient-metadata` error is indeed very strange, that makes no sense to me and looks like a false-positive (I am looking into that issue). The metadata is indeed invalid though:
```
$ appstreamcli validate kodi.metainfo.xml
E: ~:~: xml-markup-invalid
     Could not parse XML data: Entity: line 109: parser error : Premature end of data in tag
     component line 2
     
     ^
Validation failed: errors: 1
```
=> You are missing the closing `</component>` tag in the document ;-)

Then you only need to make the component-ID an rDNS string, for example `tv.kodi.kodi`, and then validation will pass :-)
Sorry for the weird error message, I guess there's an issue in out-of-context libxml2 error handling which yields the (wrong) ancient metadata message instead of the correct "broken XML" message.

**Comment by basilgello** [comment]
@ximion Is it normal that `appstreamcli validate kodi.metainfo.xml` hangs indefinitely trying to reach some HTTP resource?

**Comment by basilgello** [comment]
> Did it get lost somewhere in between? Did you copy the file by hand?

Yes, that was `quilt` bug on Debian side somehow :)
